### ISSUE TITLE
replace dates by the word 'permalink' rather than removing them

### ISSUE THREAD

**Issue by s-ol** [bengrosser/twitter-demetricator#4]
in current (new) twitter design, right/middle-clicking the date is the only way to copy the permalink to a tweet, or to open the tweet in a new tab (without opening the tweet separately and copying from the address bar). It would be very nice if there was a way to retain this functionality.

My suggestion would be to replace the date with the static string 'permalink' or a little link icon.

**Comment by bengrosser** [comment]
@s-ol for this precise reason I have only changed the opacity of that item so you can't see it (rather than removing it). In other words, you can still middle-click the area where the age metric used to be to open that tweet in a new tab. But what I'm hearing is that that wasn't obvious enough! 

I'd hate to clutter the tweet display with but agree this is essential functionality. Let me think about how to solve it. But in the meantime, let me know if you're able to do what I describe above.

**Comment by bengrosser** [comment]
I spoke too soon. At least for me, the _entire tweet_ is middle clickable to open it in a new tab. Is this not working for you? If not, let me know platform/browser?

**Comment by s-ol** [comment]
Middle-clicking the tweet content is putting me into the mouse-scroll mode.
There is no DOM element in the blank space next to the name.

Console says: 
```
Twitter Demetricator, ver. 1.1.8 -- by Ben Grosser
td.user.js:435 https://bengrosser.com/projects/twitter-demetricator/
td.user.js:436  ... loaded for URL --> https://twitter.com/
td.user.js:439  ... NEW TWITTER DETECTED (will adjust accordingly)
```

Chrome 76.0.3809.132 on windows 8.1 in this instance, although I believe it's the same on my Arch Linux setup.

In general, posts don't have any date (`<time />` tag) in the DOM at all, but some dates seem to slip through, in general like here:
![image](https://user-images.githubusercontent.com/1731279/65276539-38d26c80-db28-11e9-942f-a9da621f74bd.png)
These `time` tags here have a class `demetricator_checked` applied to them.

**Comment by s-ol** [comment]
As for this:

> I'd hate to clutter the tweet display with but agree this is essential functionality. Let me think about how to solve it.

maybe the text can be hidden until the tweet is hovered? that way there is at most one of these visible at a time.

**Comment by s-ol** [comment]
huh... tested again on ArchLinux, chromium `77.0.3865.75-1` and ctrl-clicking works. This is a bit strange.

**Comment by aaronbauman** [comment]
This appears to still or again be an issue.

I'm in Brave 1.30.86 (Chromium 94.0.4606.61) and left-click / ctrl-click doesn't work to show the "open in new tab" links, nor the "copy link location" option for the permalink.

The DOM does contain the `a href`, however it's set to `display:none` rather than the opacity change described previously.

For me personally, this is moot because of https://github.com/bengrosser/twitter-demetricator/issues/5 but maybe some people want a permalink without actually seeing the date/time

**Comment by bengrosser** [comment]
I'll look at this in next update.

Temporary workaround: you can cmd-click (Mac) any item on the feed to open
it into a new tab. I presume it's ctrl-click on PC. Contextual menu still
doesn't show the open in new tab or copy link location, but at least this
makes things possible.

**Comment by gwern** [comment]
I just came here to complain that there was no way to open a tweet in a tab or get a permalink easily, which I need because I am routinely linking & archiving research-related tweets... but I just tried the blind middle-click, which I had no idea about even after hovering carefully over where the invisible link is (because there is no mouse nor status bar change like there is for all normal links), and it seems to work. (I would point out that Firefox Demetricator is currently failing to remove dates inside retweets/quote-replies, if that is important.)

Requiring a blind click, with no cursor change or status bar indicator or other hint whatsoever, is user-hostile. No user will ever figure out where the date/permalink went. 

Anything would be better than the status quo:

- truncate it to the year
- replace with a standard anchor-chain 'permalink' icon, faded out
- make hiding/not-hiding a configurable option of the extension
- make it invisible but exposed on hover
- at least make it so the invisible link on-hover causes mouse changes/status-bar changes (so a user has a chance to discover it without hunting down & reading Github bug reports like this)
